build: Server.java ServerServerInterface.java ServerClientInterface.java RMIServer.java RMIClient.java Logger.java 
	javac RMIServer.java RMIClient.java 
	cp *.class server1
	cp *.class server2
	cp *.class server3
	cp *.class server4
	cp *.class server5

clean:
	rm server1/* server2/* server3/* server4/* server5/*
	rm *.class *.log *.obj
