build: Acceptor.java DBServer.java Logger.java Proposer.java ServerBase.java TaskType.java Client.java DBServerInterface.java OpCode.java ProposerInterface.java ServerInterface.java ClientInterface.java Learner.java Proposal.java Server.java Task.java
	javac Server.java Client.java
	cp *.class server1
	cp *.class server2
	cp *.class server3
	cp *.class server4
	cp *.class server5

clean:
	rm server1/* server2/* server3/* server4/* server5/*
	rm *.class *.log *.obj
