build: Server.java ServerInterface.java RMIServer.java RMIClient.java Logger.java TCPServer.java TCPClient.java UDPServer.java UDPClient.java HashMapParser.java
	javac RMIServer.java RMIClient.java TCPServer.java TCPClient.java UDPServer.java UDPClient.java

clean:
	rm *.class *.log
